In [41]:
import numpy as np
import pandas as pd
a = pd.read_csv("/DATA7_DB7/data/fhong/datamining2020course/course1.csv")
a=np.asarray(a)
data=a[:,1:]
idn=a[:,0]

In [26]:
data.shape

(50000, 100)

In [27]:
idn.shape

(50000,)

In [4]:
import random
def int_center(data, k=5):
    index = random.sample(range(0,49999),5)
    centers=data[index,:]
    return centers


In [5]:
def devide(data, k, centers):

    clusters = []
    for index in range(k):
        clusters.append([])

    for i,x in enumerate(data):
        dis = np.sum((x-centers)**2, axis=1)
        idx=np.argmin(dis)
        clusters[idx].append(i)

    return clusters


In [6]:
def update(data, k, clusters):
    centers = np.zeros((k, data.shape[1]))

    for idx in range(k):
        
        if len(clusters[idx]):

            tmp=np.array(clusters[idx])

            centers[idx] = np.mean(data[tmp,:], axis=0)

    return centers


In [7]:

def classify(data, k, threshold):

    centers = int_center(data, k)
    loss = float("inf")


    while loss > threshold:
       
        clusters = devide(data, k, centers)
        old_centers = centers
        centers = update(data, k, clusters)
        loss = np.sum(np.abs(old_centers - centers))
        print(" loss=%f" % (loss))

    return centers, clusters


In [10]:
centers, clusters= classify(data=data,k=5,threshold=0.1)

 loss=266.342001
 loss=81.070315
 loss=0.000000


In [11]:
for i in range(5):
    print(len(clusters[i]))

10000
10000
10000
10000
10000


In [16]:
for i in range(5):
    tmp=np.array(clusters[i])
    distance=np.sum((data[tmp,:]-centers[i])**2, axis=1)
    print(distance.shape)
    distance=np.max(distance)
    print(distance)

(10000,)
4.1708935581031445
(10000,)
4.656891069425747
(10000,)
5.554687861387594
(10000,)
5.551432076967877
(10000,)
4.9381935446020995


In [13]:
distance = np.sum((centers)**2, axis=1)
distance

array([97.45462434, 97.07561281, 96.58548564, 96.78164745, 96.90806579])

In [34]:
out= idn


In [35]:
tmp=np.array(clusters[0])
out[tmp]=0
tmp=np.array(clusters[1])
out[tmp]=1
tmp=np.array(clusters[2])
out[tmp]=4
tmp=np.array(clusters[3])
out[tmp]=3
tmp=np.array(clusters[4])
out[tmp]=2

In [36]:
out

array([0., 4., 4., ..., 4., 3., 0.])

In [42]:
idn

array([0.0000e+00, 1.0000e+00, 2.0000e+00, ..., 4.9997e+04, 4.9998e+04,
       4.9999e+04])

In [44]:
printarray=np.c_[idn,out]

In [54]:
printarray.astype(np.int)

array([[    0,     0],
       [    1,     4],
       [    2,     4],
       ...,
       [49997,     4],
       [49998,     3],
       [49999,     0]])

In [55]:
printarray.shape

(50000, 2)

In [68]:
list=printarray.tolist()
name=['id','category']
result=pd.DataFrame(columns=name,data=list)
print(result)
result.to_csv('result.csv')

            id  category
0          0.0       0.0
1          1.0       4.0
2          2.0       4.0
3          3.0       1.0
4          4.0       4.0
...        ...       ...
49995  49995.0       3.0
49996  49996.0       4.0
49997  49997.0       4.0
49998  49998.0       3.0
49999  49999.0       0.0

[50000 rows x 2 columns]
